In [3]:
import pandas as pd
import numpy as np

In [9]:
signal_history = pd.read_csv("signal_history_6_19.csv")
signal_knack = pd.read_csv("signals_knack_7_13.csv")
signal_switches_knack = pd.read_csv("ip_switches_knack_7_13.csv")

In [10]:
signal_history = signal_history.iloc[:,0:4].copy()

In [11]:
signal_history.head(10)

   SIGNAL_ID   IP_ADDRESS_ID COMM_STATUS_ID Comm_TYPE_ID
0       75.0   172.86.162.16         Online  Cell Modem
1      115.0  172.86.160.248         Online  Cell Modem
2      161.0   172.86.161.37         Online  Cell Modem
3      178.0   172.86.162.79         Online  Cell Modem
4      206.0  172.86.162.124         Online  Cell Modem
5      236.0  172.86.161.217         Online  Cell Modem
6      237.0  172.86.161.245         Online  Cell Modem
7      269.0  172.86.160.219         Online  Cell Modem
8      381.0  172.86.161.135         Online  Cell Modem
9      387.0   172.86.162.54         Online  Cell Modem

In [14]:
signal_knack = signal_knack[["SIGNAL_ID", "CONTROLLER_IP", "IP_COMM_STATUS", "COMM_TYPE"]]

In [32]:
signal_kanck = signal_knack.rename(columns = {"SIGNAL_ID":"SIGNAL_ID_KNACK"}, inplace = True)

In [33]:
signal_knack.head(10)

   SIGNAL_ID_KNACK CONTROLLER_IP    IP_COMM_STATUS COMM_TYPE
0                2  172.16.74.52            ONLINE    Switch
1                3  172.16.74.48            ONLINE    Switch
2                4  172.16.74.44            ONLINE    Switch
3                5  172.16.74.40            ONLINE    Switch
4                6  172.16.74.36            ONLINE    Switch
5                7  172.16.74.32            ONLINE    Switch
6                8           NaN  NO COMMUNICATION    Switch
7                9  172.16.74.28            ONLINE    Switch
8               10  172.16.75.28            ONLINE    Switch
9               11  172.16.74.24            ONLINE    Switch

In [41]:
signal_history.loc[signal_history["COMM_STATUS_ID"] == "No Comm Assigned", 'IP_ADDRESS_ID'] = "0.0.0.0"

In [81]:
comparison = signal_history.merge(signal_knack, left_on='SIGNAL_ID', right_on='SIGNAL_ID_KNACK', how='outer')

In [83]:
signal_switches_knack.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 899 entries, 0 to 898
Data columns (total 5 columns):
SIGNAL_ID_SWITCH    865 non-null object
SWITCH_IP           899 non-null object
SEQUENCE_ID         899 non-null int64
SIGNAL              865 non-null object
CAMERA              19 non-null object
dtypes: int64(1), object(4)
memory usage: 21.1+ KB

In [84]:
signal_switches_knack.head(5)

,SIGNAL_ID_SWITCH,SWITCH_IP,SEQUENCE_ID,SIGNAL,CAMERA
0,263,172.16.241.029,103,263: COLORADO ST / 10TH ST,NaN
1,262,172.16.241.028,7,262: LAVACA ST / 10TH ST,NaN
2,250,172.16.241.027,6,250: GUADALUPE ST / 11TH ST,NaN
3,261,172.16.241.026,5,261: GUADALUPE ST / 10TH ST,NaN
4,274,172.16.241.025,102,274: COLORADO ST / 9TH ST,NaN

In [85]:
signal_switches_knack.rename(columns = {"IP_ID":"SWITCH_IP", "signal": "SIGNAL", "camera": "CAMERA"}, inplace = True)

In [86]:
signal_switches_knack = signal_switches_knack[["SIGNAL_ID_SWITCH", "SWITCH_IP", "SEQUENCE_ID", "SIGNAL", "CAMERA"]].copy()

In [93]:
comparison[comparison["SIGNAL_ID"].isnull()]

,SIGNAL_ID,IP_ADDRESS_ID,COMM_STATUS_ID,Comm_TYPE_ID,SIGNAL_ID_KNACK,CONTROLLER_IP,IP_COMM_STATUS,COMM_TYPE,diff
955,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,no
956,NaN,NaN,NaN,NaN,8.0,NaN,NO COMMUNICATION,Switch,no
957,NaN,NaN,NaN,NaN,18.0,NaN,NO COMMUNICATION,Switch,no
958,NaN,NaN,NaN,NaN,22.0,NaN,NO COMMUNICATION,Switch,no
959,NaN,NaN,NaN,NaN,34.0,NaN,NO COMMUNICATION,Switch,no
960,NaN,NaN,NaN,NaN,36.0,NaN,NO COMMUNICATION,Switch,no
961,NaN,NaN,NaN,NaN,41.0,NaN,NO COMMUNICATION,Switch,no
962,NaN,NaN,NaN,NaN,72.0,NaN,NO COMMUNICATION,Switch,no
963,NaN,NaN,NaN,NaN,77.0,NaN,NO COMMUNICATION,Switch,no
964,NaN,NaN,NaN,NaN,97.0,NaN,NO COMMUNICATION,Switch,no
965,NaN,NaN,NaN,NaN,104.0,NaN,NO COMMUNICATION,Switch,no
966,NaN,NaN,NaN,NaN,127.0,NaN,NO COMMUNICATION,Switch,no
967,NaN,NaN,NaN,NaN,136.0,NaN,NO COMMUNICATION,Switch,no
968,NaN,NaN,NaN,NaN,147.0,NaN,NO COMMUNICATION,Switch,no
969,NaN,NaN,NaN,NaN,157.0,NaN,NO COMMUNICATION,Switch,no
970,NaN,NaN,NaN,NaN,167.0,NaN,NO COMMUNICATION,Switch,no
971,NaN,NaN,NaN,NaN,173.0,NaN,NO COMMUNICATION,Switch,no
972,NaN,NaN,NaN,NaN,212.0,NaN,NO COMMUNICATION,Switch,no
973,NaN,NaN,NaN,NaN,225.0,172.16.105.44,ONLINE,Switch,no
974,NaN,NaN,NaN,NaN,323.0,NaN,NO COMMUNICATION,Switch,no
975,NaN,NaN,NaN,NaN,331.0,NaN,NO COMMUNICATION,Switch,no
976,NaN,NaN,NaN,NaN,334.0,NaN,NO COMMUNICATION,Switch,no
977,NaN,NaN,NaN,NaN,336.0,NaN,NO COMMUNICATION,Switch,no
978,NaN,NaN,NaN,NaN,339.0,NaN,NO COMMUNICATION,Switch,no
979,NaN,NaN,NaN,NaN,340.0,NaN,NO COMMUNICATION,Switch,no
980,NaN,NaN,NaN,NaN,345.0,NaN,NO COMMUNICATION,Switch,no
981,NaN,NaN,NaN,NaN,380.0,NaN,NO COMMUNICATION,Switch,no
982,NaN,NaN,NaN,NaN,385.0,NaN,NO COMMUNICATION,Switch,no
983,NaN,NaN,NaN,NaN,386.0,NaN,NO COMMUNICATION,Switch,no
984,NaN,NaN,NaN,NaN,391.0,NaN,NO COMMUNICATION,Switch,no
...,...,...,...,...,...,...,...,...,...
1088,NaN,NaN,NaN,NaN,992.0,NaN,NO COMMUNICATION,Switch,no
1089,NaN,NaN,NaN,NaN,993.0,NaN,NO COMMUNICATION,Switch,no
1090,NaN,NaN,NaN,NaN,1001.0,NaN,NO COMMUNICATION,Switch,no
1091,NaN,NaN,NaN,NaN,1002.0,NaN,NO COMMUNICATION,Switch,no
1092,NaN,NaN,NaN,NaN,1003.0,NaN,NO COMMUNICATION,Switch,no
1093,NaN,NaN,NaN,NaN,1012.0,NaN,NO COMMUNICATION,Switch,no
1094,NaN,NaN,NaN,NaN,1021.0,NaN,NO COMMUNICATION,Switch,no
1095,NaN,NaN,NaN,NaN,1025.0,NaN,NO COMMUNICATION,Switch,no
1096,NaN,NaN,NaN,NaN,1028.0,NaN,NO COMMUNICATION,Switch,no
1097,NaN,NaN,NaN,NaN,1032.0,NaN,NO COMMUNICATION,Switch,no
1098,NaN,NaN,NaN,NaN,1038.0,NaN,NO COMMUNICATION,Switch,no
1099,NaN,NaN,NaN,NaN,1039.0,NaN,NO COMMUNICATION,Switch,no
1100,NaN,NaN,NaN,NaN,1040.0,NaN,NO COMMUNICATION,Switch,no
1101,NaN,NaN,NaN,NaN,1041.0,NaN,NO COMMUNICATION,Switch,no
1102,NaN,NaN,NaN,NaN,1042.0,NaN,NO COMMUNICATION,Switch,no
1103,NaN,NaN,NaN,NaN,1044.0,NaN,NO COMMUNICATION,NaN,no
1104,NaN,NaN,NaN,NaN,1048.0,NaN,NO COMMUNICATION,NaN,no
1105,NaN,NaN,NaN,NaN,1049.0,NaN,NO COMMUNICATION,NaN,no
1106,NaN,NaN,NaN,NaN,4020.0,NaN,NO COMMUNICATION,Switch,no
1107,NaN,NaN,NaN,NaN,4055.0,NaN,NO COMMUNICATION,Switch,no
1108,NaN,NaN,NaN,NaN,4056.0,NaN,NO COMMUNICATION,Switch,no
1109,NaN,NaN,NaN,NaN,4057.0,NaN,NO COMMUNICATION,Switch,no
1110,NaN,NaN,NaN,NaN,4058.0,NaN,NO COMMUNICATION,Switch,no
1111,NaN,NaN,NaN,NaN,4059.0,NaN,NO COMMUNICATION,Switch,no
1112,NaN,NaN,NaN,NaN,4079.0,NaN,NO COMMUNICATION,Switch,no
1113,NaN,NaN,NaN,NaN,4080.0,NaN,NO COMMUNICATION,Switch,no
1114,NaN,NaN,NaN,NaN,4081.0,NaN,NO COMMUNICATION,NaN,no
1115,NaN,NaN,NaN,NaN,4082.0,NaN,NO COMMUNICATION,NaN,no
1116,NaN,NaN,NaN,NaN,4083.0,NaN,NO COMMUNICATION,NaN,no
1117,NaN,NaN,NaN,NaN,4084.0,NaN,NO COMMUNICATION,NaN,no

In [94]:
comparison = comparison[np.isfinite(comparison['SIGNAL_ID'])].copy()

In [95]:
comparison["SIGNAL_ID"] = comparison["SIGNAL_ID"].astype(np.int64).astype(str)

In [96]:
signal_switches_knack["SIGNAL_ID_SWITCH"] = signal_switches_knack["SIGNAL"].str.split(":", expand=True)[0]

In [97]:
comparison = comparison.merge(signal_switches_knack, left_on='SIGNAL_ID', right_on='SIGNAL_ID_SWITCH', how='outer')

In [98]:
comparison.head(5)

,SIGNAL_ID,IP_ADDRESS_ID,COMM_STATUS_ID,Comm_TYPE_ID,SIGNAL_ID_KNACK,CONTROLLER_IP,IP_COMM_STATUS,COMM_TYPE,diff,SIGNAL_ID_SWITCH,SWITCH_IP,SEQUENCE_ID,SIGNAL,CAMERA
0,75,172.86.162.16,Online,Cell Modem,75.0,0.0.0.0,ONLINE,No Communication,no,75,172.16.207.090,105.0,75: US 290 HWY / HUDSON LOOP,NaN
1,115,172.86.160.248,Online,Cell Modem,115.0,172.86.160.248,OFFLINE,Cell Modem,yes,115,172.16.154.133,101.0,115: BARTON SPRINGS RD / STRATFORD DR,NaN
2,161,172.86.161.37,Online,Cell Modem,161.0,172.16.109.24,OFFLINE,No Communication,no,161,172.16.152.096,101.0,161: SPRINGDALE RD / OAK SPRINGS DR,NaN
3,178,172.86.162.79,Online,Cell Modem,178.0,0.0.0.0,ONLINE,Cell Modem,no,NaN,NaN,NaN,NaN,NaN
4,206,172.86.162.124,Online,Cell Modem,206.0,172.86.162.124,OFFLINE,Cell Modem,yes,206,172.16.207.094,109.0,206: SOUTHWEST PKWY / FOSTER RANCH RD,NaN

In [ ]:
comparison["diff"] = np.where(comparison["CONTROLLER_IP"] == comparison["IP_ADDRESS_ID"], "yes", "no")